# Configuração Mínima para Periféricos e RTOS

# 1. Suporte Geral a Drivers
CONFIG_GPIO=y      # Para LEDs e Botões
CONFIG_PWM=y       # Para o Gerador de Sinal (SigGen)

# 2. Suporte UART / Comunicação Assíncrona
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_ASYNC_API=y    # CRÍTICO: Para a Command Processor Thread não bloquear

# 3. Componentes RTOS (já deve estar ativo, mas é bom confirmar)
CONFIG_MULTITHREADING=y  

# 4. Suporte a ponto flutuante (Crucial para Amplitude e Cálculos de Onda)
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y       # Para permitir funções matemáticas complexas (sin/cos)