CONFIG_LOG=y

CONFIG_PWM=y

CONFIG_LED=y

CONFIG_LOG_MODE_IMMEDIATE=y

# Habilita o subsistema de console
CONFIG_CONSOLE=y 

# Habilita o suporte UART (necessário para a comunicação serial)
CONFIG_UART_CONSOLE=y

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CBPRINTF_FP_SUPPORT=y
