CONFIG_LOG=y

CONFIG_PWM=y

CONFIG_LED=y

CONFIG_LOG_MODE_IMMEDIATE=y

# Habilita o subsistema de console
CONFIG_CONSOLE=y 

# Habilita o suporte UART (necessário para a comunicação serial)
CONFIG_UART_CONSOLE=y
